### ISSUE TITLE
On Chrome, audio can be out of sync 

### ISSUE THREAD

**Issue by ludotex** [joshwcomeau/beatmapper#18]
Most of the time, unless it's from the start of the song, the audio from the song is a little out of sync with the blocks (while starting playing at any bar from the song other than the start).

Works fine on Explorer (which is not supported)

**Comment by joshwcomeau** [comment]
Interesting - I haven't seen this one before, although

Some questions to help me find the problem:

- There are a few different ways to seek through the song: using the mousewheel, scrubbing on the waveform, or just playing/pausing repeatedly. Does the problem happen with all methods? What if you press `j` and enter a bar number?
- is it predictably out-of-sync (eg. always off by 200ms) or is it random / always off by a different amount?
- In the bottom right there's a little toggle to play a tick sound on every block. Is the ticking synched to the music (and out-of-sync with the blocks), or in-sync with the blocks (and out of sync with the music), or totally out of sync with everything?

**Comment by ludotex** [comment]
I cannot reproduce this anymore.
I was using the click sound and the mouse wheel scroll (1 bar setting) at the time.

I tried with a click track generated from audacity (generate -> rythm track) and it is pretty rock solid. Maybe the click sound is a tiny bit of the click track but this could be the sound used from the click track.
Maybe my machine was lagging a bit earlier (with some other processes running).

**Comment by ludotex** [comment]
Coming back to this issue:
I think there is a little problem here still.

I have a song that is 160 bpm.
I had to put it at 160,05 bpm in beatmapper to match the click and beats in beatmapper, otherwise in beatmapper it started to drift late.
But when I play it in beat saber (at 160,05 bpm)  it starts to drift, by 2 or 3 minutes times, you can hear maybe  it's getting of the beat by 1/8 beat. Which is weird because it sounds fine in beatmapper. So I am thinking there might be a little precision or conversion issue here maybe.

I tried in MM at 160 bpm and it works fine in MM and beat saber (which is the correct behavior I expected)

It's a bit confusing, I hope you get my point and can reproduce it hopefully.

**Comment by ludotex** [comment]
Scrap that, I shouldn't have put the 160,05 bpm in the first place to try to correct the drift. There is no drift. 
I think my confusion came from the sound of the click that is 60 ms off the beat. I have to put an offset of -60 to get a good matching click sound. Hence the source of all my confusion.

For example on the demo song, i put 1511 as the offset value I get a much better matching click sound.


I am on chrome on windows. Is it the same on your machine? If so maybe you can offset the click sound instead of having to do it on the map :)

**Comment by joshwcomeau** [comment]
Ahh, right - yeah, so I'm aware of this problem (sadly I've spent a good chunk of time trying to fix it, and while it's way better than it used to be, it's still definitely off).

Sadly it's not as simple as offsetting it by 60ms since the amount of time varies depending on the device. On my iMac Pro it's only 20-30ms or so, while on my laptop it's more noticeable, maybe 80-90ms.

I debated getting rid of the tick but I think it's still useful to give the mapper a sense of the rhythm of blocks. It's just not accurate enough to be used to synchronize the music to the map (my assumption is that folks will figure out the BPM/offset in another program and come to Beatmapper with that info already).

I think I'll add a popup that shows up when the user clicks the tick SFX for the first time, to explain that it's slightly delayed. That, or maybe take another crack at trying to fix it 🤔

**Comment by ludotex** [comment]
Or maybe add a slider to manually offset the tick in the (incoming) option menu ?

**Comment by joshwcomeau** [comment]
@ludotex when you have a sec, could you try it again? I reconfigured this, and added a fake delay. Testing on two wildly different machines (a dusty media-center PC that takes forever to do anything vs. an iMac Pro) and it somehow seems to work alright for both?

Might add it as an option, but for now I think I found a value "close enough" for everyone

**Comment by ludotex** [comment]
Heya. Just tried, it's still a bit early maybe, but frankly I think its good enough for mapping need. Grats on finding on a middle ground value for everyone :)

**Comment by joshwcomeau** [comment]
awesome :+1: Yeah, I might still make it an option, but for now this is sufficient
