### ISSUE TITLE
Click and drag to rotate block doesnt work ?

### ISSUE THREAD

**Issue by ludotex** [joshwcomeau/beatmapper#19]
Unless I am mistaken, but i couldnt figure out how to rotate the block with click and drag (on Chrome).
Doc says:

> Finally, you can click and drag to dynamically select a block direction. This is my personal favourite way to place blocks:

**Comment by joshwcomeau** [comment]
hey @ludotex,

Hm, the only thing that comes to mind is maybe you have a different tool selected? Do you have red/blue blocks selected in the sidebar?

<img width="293" alt="Screen Shot 2019-09-24 at 10 30 10 AM" src="https://user-images.githubusercontent.com/6692932/65520894-5bf97500-deb6-11e9-99aa-8fc7abfa3b92.png">

Alternatively, maybe the docs are explaining how to do it poorly. It works by clicking an empty cell and dragging in any direction:

![drag](https://user-images.githubusercontent.com/6692932/65521028-96631200-deb6-11e9-82be-3102449603b9.gif)

If you're doing this and it's not working, can you let me know if there are any errors in the dev console? And include a recording, so I can see if any other factors might be at play?

**Comment by ludotex** [comment]
Ok got it now, it works fine. 

I wasn't draging from an empty cell. 
I was clicking to put the note and then clicking again outside of the grid and expected a rotation from the last put cube.

wish list: it would be nice to be able to rotate an already placed cube :)

**Comment by joshwcomeau** [comment]
> wish list: it would be nice to be able to rotate an already placed cube :)

Yeah that's a good point. It's weird that the behaviour isn't consistent / shared for existing blocks.

One issue though is that clicking an existing cube selects it, and it might be weird / overloaded to support both :/ 

Glad the issue is resolved :) let me know if you think of any other quality-of-life tweaks I could make!

**Comment by ludotex** [comment]
Maybe right mouse button to rotate as left mouse is used for selection?

**Comment by ludotex** [comment]
Nevermind right mouse is delete already...
