### ISSUE TITLE
Click sound doesnt sound on 1/8 beats

### ISSUE THREAD

**Issue by ludotex** [joshwcomeau/beatmapper#20]
Set the precision to 1/8 beat
Place for example a block on 3/8 of the beat. The click wont sound for this block.

**Comment by joshwcomeau** [comment]
Good catch! I was aware of this, it's one of those things where I was hoping folks wouldn't notice 😅for complicated reasons I only somewhat remember I was having performance issues with the clicks so I'm currently "faking" it, and faking it on every frame was too expensive.

Sorry if it caused confusion! This has been on my list to fix for a bit, but it's not super high priority. Lemme know if there's a reason you think this should be bumped up the list

**Comment by ludotex** [comment]
Totally low priority for me. Just wanted to let you know :)

**Comment by joshwcomeau** [comment]
This should be fixed now :D
