### ISSUE TITLE
Ctrl+key doesn't disable unmodified key

### ISSUE THREAD

**Issue by murapix** [joshwcomeau/beatmapper#21]
Using ctrl+1-4 switches between beat snap settings fine, but also switches between the selected item (block, mine, or wall). The intended result is that the beat snap setting would change, but the selected item type would remain unchanged.

Also, sorry about the edits, keep accidentally pressing extra keys on this keyboard.

**Comment by joshwcomeau** [comment]
Good catch! This should be a really quick fix, I'll get it out asap :)

**Comment by joshwcomeau** [comment]
Just merged a fix for this, should get deployed in the next few minutes
