### ISSUE TITLE
Swap out song and icon

### ISSUE THREAD

**Issue by murapix** [joshwcomeau/beatmapper#22]
A couple times I've had to switch out the audio file for a track I've already started, due to it having been too quiet or too long. Having the option to change the audio file, and the image as well, would save a lot of trouble in switching over.

**Comment by joshwcomeau** [comment]
Yeah, good point. This would be a pretty big quality-of-life boost, and it shouldn't be too hard to implement.

Adding it to my list.

**Comment by joshwcomeau** [comment]
Shipping this fix now! You can now edit audio and cover art from the "song details" page (5th icon in the sidebar).

let me know if you run into any problems :)
