### ISSUE TITLE
Overwriting a song already loaded keeps the old one

### ISSUE THREAD

**Issue by ludotex** [joshwcomeau/beatmapper#24]
Say you have a song already created that you load throught the main menu. If you import another version of that same song, it will warn you have a duplicate, you click yes to overwrite. However the editor is still loaded with the previous version.

**Comment by joshwcomeau** [comment]
Good catch!

I just poked around with this and I _think_ I've fixed it. Can you give it a try again and let me know what the result is? :)

**Comment by ludotex** [comment]
Yes, looks like its working now!

**Comment by joshwcomeau** [comment]
Awesome, thanks :)
