### ISSUE TITLE
3D view resets after saving menu

### ISSUE THREAD

**Issue by ludotex** [joshwcomeau/beatmapper#26]
I save often, and I have to redo the 3D camera view everytime I come back to the editor. 
Would be nice if it kept the view as it was before :)

**Comment by joshwcomeau** [comment]
Hm, the thing is I suspect some people might like that it resets. Feels like it gives you a clean start when you reload a map.

One thing you can do: Cmd+S (or ctrl+S on windows) downloads the current map, so you don't have to leave the notes tab so often

**Comment by joshwcomeau** [comment]
(I'm working on creating a master list of keyboard shortcuts! Hopefully that'll help make stuff like this clear)

**Comment by ludotex** [comment]
Ah nice, ctrl+S is even better than going thru a menu!

**Comment by joshwcomeau** [comment]
Sweet :) Gonna close this since I think there's value in having the camera reset
