### ISSUE TITLE
Pasting notes, pastes upside down

### ISSUE THREAD

**Issue by ludotex** [joshwcomeau/beatmapper#27]
Copy paste some notes. The pasted notes are up side down.
(on windows + chrome)

**Comment by joshwcomeau** [comment]
Ahh right - I recently added a `v` hotkey to do the "vertical" swap (like how `h` does horizontal). I need to make sure it doesn't trigger that when pasting. In the meantime, you can press `v` again after pasting to flip them

**Comment by joshwcomeau** [comment]
Pushing a fix for this now! If it isn't fixed in ~5min, plz let me know :)
