### ISSUE TITLE
Invalid Hotkey Usage with Modifiers

### ISSUE THREAD

**Issue by murapix** [joshwcomeau/beatmapper#29]
More of the same issue with #21, but this time with ctrl+z and ctrl+v. This is definitely in a build including the fix for #21, make sure you do this for *all* keybinds and their modifier keys (ctrl, alt, shift, etc.).

**Comment by joshwcomeau** [comment]
The fix for ctrl+v went out about an hour before you opened this issue (see: #27), and the Z key is only used for undo/redo, does nothing when the modifier key isn't held. So I believe all keybind issues are currently resolved, but let me know if anything is still occurring.
