### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by henwill8** [joshwcomeau/beatmapper#37]
In the notes page, the notes will load for a couple of seconds but then it will disappear and I cant do anything: 
![image](https://user-images.githubusercontent.com/43818215/66722629-6af48880-edcd-11e9-940f-ca2db46aaad6.png)
Also, if I then go to a different page such as the lights page or something and then go back, everything will stop and it will say an error occurred in the top left of the screen.

**Comment by joshwcomeau** [comment]
hey @henwill8,

Haven't seen this issue before - can you let me know if there are any errors in the console? You can open the console with ctrl+shift+i, I believe (cmd+shift+i on a mac).

Also, if possible, can you download the map and email it to me at joshwcomeau@gmail.com? I'll take a look and see if I can spot anything with the files.

**Comment by henwill8** [comment]
Just suddenly, it wont respond at all, after a couple of reloads, now it just shows a black screen even if I exit the page and open it again.

**Comment by henwill8** [comment]
I might try to restart my computer

**Comment by henwill8** [comment]
I checked the console of this new error, here is a screenshot of it:
![image](https://user-images.githubusercontent.com/43818215/66722744-bbb8b100-edce-11e9-9128-e1b6adb81e96.png)

**Comment by henwill8** [comment]
Restarting my computer fixed the second problem but still the first one remains. It seems I am still able to interact with the notes, just the model isnt loading. The console looks the same as when it wouldnt load at all.

**Comment by henwill8** [comment]
@joshwcomeau I sent you the file of the map

**Comment by henwill8** [comment]
Console says enable javascript but I just checked and I have it enabled for all apps

**Comment by joshwcomeau** [comment]
Hey @henwill8 - got the email, and the song loads for me. So it's likely not something related to the song file... Not sure what it could be.

The screenshot you shared shows that there are 5 console errors, but they're on another tab. Could you please click "Console" in the top bar (to the right of "Elements) and share what it says there?

**Comment by henwill8** [comment]
@joshwcomeau Here:
![image](https://user-images.githubusercontent.com/43818215/66755692-c23e3b80-ee55-11e9-99e2-314b2df1657a.png)

**Comment by joshwcomeau** [comment]
Thanks for sharing. Unfortunately I've never seen that issue before :/

I did some research and it seems to be a weird thing that happens sometimes. If you haven't already, can you try restarting your computer? Possible it just got into a weird state. Also, I see that you're on Chrome 75 - it might be helpful to update to Chrome 77 (it really _shouldn't_ matter, but you never know)

**Comment by henwill8** [comment]
I have tried restarting my computer, didnt work. I'll update chrome and check after.

**Comment by henwill8** [comment]
Updating chrome chrome didnt work. :(

**Comment by joshwcomeau** [comment]
Hm, sorry to hear that :( honestly I'm not sure what's going on, and with no way to reproduce it, I'm not sure how I could fix it.

I'll post here if I figure anything out, or find a way to reproduce

**Comment by joshwcomeau** [comment]
hey @henwill8 - sounds like a browser setting might be to blame here! Can you try the suggestion in https://github.com/joshwcomeau/beatmapper/issues/45?

**Comment by henwill8** [comment]
Oh, yeah recently I have noticed that my browser can't use webgl, I'll try this when I next get on my computer.

**Comment by henwill8** [comment]
6th

**Comment by henwill8** [comment]
Accidently closed it on my phone

**Comment by henwill8** [comment]
Use hardware acceleration when available didn't work. It was already checked so I unchecked relaunched then checked it again and relaunched and it still didnt work. I will try downloading a different browser and trying it.

**Comment by henwill8** [comment]
I used this website to see if my computer supports webgl and it says it does:https://webglreport.com/

**Comment by henwill8** [comment]
Got it working by going to chrome://flags// and enabling "Override software rendering list"

**Comment by henwill8** [comment]
Got firefox, its performance for beatmapper is much higher than on chrome
