### ISSUE TITLE
Desktop app?

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/beatmapper#7]
A shocking number of people I've spoken to about this editor want it to be a downloadable desktop application.

I was initially resistant to this idea because I spent a _lot_ of time making everything work in-browser, it wasn't an easy feat! And I do still want there to be a browser-based version; One of the big issues I had with MediocreMapper was the amount of friction to get started, I want my editor to be effortless to use, and downloading 100mb+ (as it would be, for an Electron app) is a burden.

But, I do see a few compelling advantages:
- Dedicated icon in the tray, desktop shortcuts, etc. All the UX perks of a desktop application
- Only one open session at a time. It can be a real issue if you accidentally have multiple BeatMapper tabs open, you can accidentally erase progress in 1 tab by doing anything in another tab.
- It's what everyone else is doing, so it's an easier transition. Some people might just assume that if it works in a browser, it can't be as good 🙃
- Truly persistent file storage. Right now I'm storing files as blobs in IndexedDB, but the browser can clear this. With an Electron app I could legit save files on the user's HDD. Maybe even make it easier to go from BeatMapper to Beat Saber on PC?

It shouldn't be that much trouble to create a desktop app (famous last words), as it would just be a thin electron wrapper around the page. I wouldn't take many (any?) steps to match desktop-app conventions, it would just be the same deal but in a nice wrapper.

**Comment by themostprime** [comment]
There's a really cool utility called Nativefier (https://github.com/jiahaog/nativefier) that may be a good starting point! It'll put the built version of the app in a simple Electron wrapper with its own instance of Chromium (IIRC you can even specify the version to ship with).

That would take care of a couple sessioning issues, and at least make it easier to run, but building a true Electron version with persistent file storage is a pretty involved process. There may be an easier way to do it, but I'd imagine you'd have to turn all file storage calls into `ipc` messages (which is how Electron communicates between the rendering and main processes) to be handled by the native filesystem, then spoof the handling with an event emitter for the browser and use your existing methods there.

**Comment by joshwcomeau** [comment]
> There's a really cool utility called Nativefier (https://github.com/jiahaog/nativefier) that may be a good starting point! It'll put the built version of the app in a simple Electron wrapper with its own instance of Chromium (IIRC you can even specify the version to ship with).

Oh cool! Seems like this is the perfect short-term solution, to offer a desktop app without having to do a bunch of upfront work. Thanks for the tip =)

> building a true Electron version with persistent file storage is a pretty involved process. There may be an easier way to do it, but I'd imagine you'd have to turn all file storage calls into ipc messages (which is how Electron communicates between the rendering and main processes) to be handled by the native filesystem, then spoof the handling with an event emitter for the browser and use your existing methods there.

Yeah, that's about what I had in mind. One good thing: recognizing that my current file-storage system was not great, I have an intermediate layer with a custom API for saving/accessing files, so I _should_ just be able to update a single file and not need to fuss with all the places that call those methods.

I've worked with Electron a little ([Guppy](https://github.com/joshwcomeau/guppy) is an Electron app) and I believe because it fuses the Chromium and Node runtimes, you can do stuff like access the `fs` module from within a rendering thread, so I don't _think_ I'd need to fuss with message-passing (although maybe that's the "proper" way to do it, for performance reasons?)

**Comment by joshwcomeau** [comment]
For now, PWAs seem to solve this quite nicely =)
