### ISSUE TITLE
Option to disable wall size/position limitations

### ISSUE THREAD

**Issue by murapix** [joshwcomeau/beatmapper#78]
While it is good to have these limitations on walls by default, there are times when people would want to be more precise about the size of their walls, usually for decorative purposes. I know that we can just enable Mapping Extensions to get the same effect, but this then removes the ability for the map to be ranked.

**Comment by joshwcomeau** [comment]
Hm not sure I follow - do you mean the limitation around not having 3-wide walls? Or the fact that you can't change the grid size unless Mapping Extensions is enabled?

Maybe you're saying that walls can be placed outside the typical grid (so, lanes greater than 3 or less than 0), without mapping extensions? 

Appreciate the heads up, and sorry it took me so long to respond! My schedule is pretty hectic right now, so I don't imagine I'll have too much time to work on this for a while =(

**Comment by murapix** [comment]
I mean the limitation where walls can only be one tall if they're in the top lane - thinking about it, that's the only one that I've seen used at all without Mapping Extensions. Scratch my original request, I'm changing it to just be allowing single-height-walls on lanes 0 and 3, rather than only in the top row.

**Comment by murapix** [comment]
And don't worry about your schedule, I know you're a single dev with a life, and this is just a request, not a requirement

**Comment by joshwcomeau** [comment]
> I mean the limitation where walls can only be one tall if they're in the top lane - thinking about it, that's the only one that I've seen used at all without Mapping Extensions

Can you link me to a map that does this? AFAIK it isn't possible, since in the original game, you don't specify heights at all, there's just two types (one for 'wall', one for 'ceiling')

**Comment by murapix** [comment]
You're correct here, I've made a wrong assumption, thinking that because MediocreMapper allowed it without any mods enabled, it was a valid option in the actual game.
