### ISSUE TITLE
An error has occurred :(

### ISSUE THREAD

**Issue by OMN30** [joshwcomeau/beatmapper#85]
I keep getting "An error has occurred :(" in the editor after 2 seconds, what can I do about it?

**Comment by joshwcomeau** [comment]
Sorry to hear that. Some thoughts:

- If you're not using Chrome, can you try it in Chrome? Haven't tested much in other browsers
- Is there anything logged in the console?

**Comment by OMN30** [comment]
It's working now, it turns out the song I used was too short.
