### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by iPuRelite** [joshwcomeau/beatmapper#86]
Hi Josh,
I read your notes about publishing and that it’s only valid at the time of writing the notes, well as you stated in your notes beat saver and the other one have changed how they accept the file. I don’t suppose you know the way around it? I have tried myself by solving each of the error messages from beat saver for example to no avail.

As you can tell I’m lost and would love a hand and l know you are busy but when you get a moment. TIA

**Comment by joshwcomeau** [comment]
Sorry for the delay on this! I don't check these issues too often.

I've successfully published a map of mine recently, so I wonder if I've since fixed the issue you reported?

**Comment by joshwcomeau** [comment]
Gonna close for now but feel free to add more details

**Comment by jacob-shuman** [comment]
Hi! I'm experiencing the same issue as well @joshwcomeau .

The error im getting on beat saver is: "Beatmap zip contains an illegal file!"

When i export my map from beatmapper i get the following layout:
info.dat
song.egg (should this not be .ogg?)
cover.jpeg
Normal.dat (i have only made a normal difficulty map)

**Comment by iPuRelite** [comment]
> Hi! I'm experiencing the same issue as well @joshwcomeau .
> 
> The error im getting on beat saver is: "Beatmap zip contains an illegal file!"
> 
> When i export my map from beatmapper i get the following layout:
> info.dat
> song.egg (should this not be .ogg?)
> cover.jpeg
> Normal.dat (i have only made a normal difficulty map)

I haven’t tried it recently but my way round it was to use BMBF & dragged the zip directly into my headset.

**Comment by jacob-shuman** [comment]
> > Hi! I'm experiencing the same issue as well @joshwcomeau .
> 
> > 
> 
> > The error im getting on beat saver is: "Beatmap zip contains an illegal file!"
> 
> > 
> 
> > When i export my map from beatmapper i get the following layout:
> 
> > info.dat
> 
> > song.egg (should this not be .ogg?)
> 
> > cover.jpeg
> 
> > Normal.dat (i have only made a normal difficulty map)
> 
> 
> 
> I haven’t tried it recently but my way round it was to use BMBF & dragged the zip directly into my headset. 

That would work as a temporary solution! Thank you!

**Comment by joshwcomeau** [comment]
Hey Jacob - so hm, I uploaded a map a week ago and it didn’t give me any grief. Sounds like there’s some edge-case with certain fields/settings. 

If the BMBF workaround fails, I’d say that you should download a couple new maps from beatsaver and compare the data files to see if anything seems different. Unfortunately, I don’t have any free time ATM so I can’t dig into this. 

(As weird as it is, .egg isn’t a mistake. For some reason it requires the extension to be changed 🤷🏻‍♂️)

**Comment by jacob-shuman** [comment]
> Hey Jacob - so hm, I uploaded a map a week ago and it didn’t give me any grief. Sounds like there’s some edge-case with certain fields/settings. 
> 
> 
> 
> If the BMBF workaround fails, I’d say that you should download a couple new maps from beatsaver and compare the data files to see if anything seems different. Unfortunately, I don’t have any free time ATM so I can’t dig into this. 
> 
> 
> 
> (As weird as it is, .egg isn’t a mistake. For some reason it requires the extension to be changed 🤷🏻‍♂️)

That’s so weird but I’m glad that it’s just an issue on my end. Thanks!
