### ISSUE TITLE
Song playback speed fails to change platform speed

### ISSUE THREAD

**Issue by murapix** [joshwcomeau/beatmapper#91]
Changing the playback speed correctly modifies the speed at which the song plays, but the platform seems to ignore this and instead always moves at the default speed.

**Comment by murapix** [comment]
Potentially related (but debugging showed it's most likely not), changing the playback speed while the song is not currently playing causes this exception to be thrown
```
asyncToGenerator.js:6 Uncaught (in promise) TypeError: Cannot read property 'playbackRate' of undefined
    at e.value (audio.service.js:39)
    at song.middleware.js:600
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
```

**Comment by joshwcomeau** [comment]
Thanks to @joshuatz , this should be fixed momentarily (after a deploy, ~5min)
