### ISSUE TITLE
Wrong colors?

### ISSUE THREAD

**Issue by Prasparadastra** [joshwcomeau/beatmapper#92]
Hello. I couldn't figure out what's with my colors.
Even though I'm using default colors (Blue and Red), I'm getting some odd Yellow and Magenta sabers & blocks. I've enabled Custom Colors once, now it is disabled. I have never selected the colors somehow close to this.
What's wrong?

![err](https://user-images.githubusercontent.com/62256798/76781713-35126080-67c0-11ea-915c-95e9bb8e650b.png)
[izba-hodit-hodunom_20200316T1932.zip](https://github.com/joshwcomeau/beatmapper/files/4339331/izba-hodit-hodunom_20200316T1932.zip)

**Comment by joshwcomeau** [comment]
Hey there - these are the default colors for the "Origins" environment. 

Not sure why the lighting is blue, but I don't think this is related to the beatmap file; there isn't any color information in the file, so maybe this is just how the game treats custom maps using this environment.
